import React, { useState, useRef } from 'react'
import BookCollection from './BookCollection'

const MainBody = () => {

    const [tempData, setTempData] = useState([
        {
            "author_key": [
                "OL7315784A"
            ],
            "author_name": [
                "Colleen Hoover"
            ],
            "first_publish_year": 2012,
            "language": [
                "pol",
                "fre",
                "ger",
                "por",
                "spa",
                "dut",
                "kor",
                "eng",
                "tur"
            ],
            "lccn": [
                "2016025388"
            ],
            "number_of_pages_median": 384,
            "title": "It Ends With Us",
            "subject": [
                "Fiction, Romance, Contemporary, Life change events",
                "Triangles (Interpersonal relations)",
                "Man-woman relationships",
                "Neurosurgeons",
                "First loves",
                "Businesswomen",
                "Fiction",
                "Contemporary Women",
                "New York Times bestseller",
                "Fiction, romance, contemporary",
                "Man-woman relationships, fiction",
                "Fiction, women",
                "collectionid:nyt2020s"
            ],
            "person": [
                "Lily",
                "atlas",
                "Ryle"
            ],
            "ratings_average": 4.209961,
            "readinglog_count": 42721,
            "subject_key": [
                "businesswomen",
                "collectionidnyt2020s",
                "contemporary_women",
                "fiction",
                "fiction_romance_contemporary",
                "fiction_romance_contemporary_life_change_events",
                "fiction_women",
                "first_loves",
                "man-woman_relationships",
                "man-woman_relationships_fiction",
                "neurosurgeons",
                "new_york_times_bestseller",
                "triangles_(interpersonal_relations)"
            ]
        },
        {
            "author_key": [
                "OL23919A"
            ],
            "author_name": [
                "J. K. Rowling"
            ],
            "first_publish_year": 1997,
            "language": [
                "swe",
                "tha",
                "tib",
                "gle",
                "urd",
                "por",
                "jpn",
                "ice",
                "kal",
                "hin",
                "ltz",
                "ara",
                "lav",
                "fre",
                "chi",
                "dut",
                "gre",
                "eng",
                "bul",
                "pol",
                "ita",
                "mar",
                "afr",
                "grc",
                "rum",
                "cat",
                "kor",
                "heb",
                "cze",
                "vie",
                "hrv",
                "hun",
                "lat",
                "rus",
                "per",
                "dan",
                "fin",
                "lit",
                "wel",
                "ger",
                "alb",
                "spa",
                "ukr",
                "gla",
                "tur",
                "ben"
            ],
            "lccn": [
                "2014381788",
                "99050266",
                "2009277057",
                "2009345731",
                "2011312476",
                "2012371961",
                "2002534901",
                "2010512633",
                "97039059",
                "2002534899",
                "2003054578",
                "2002534898",
                "2011432158",
                "2010325305",
                "2015009929"
            ],
            "number_of_pages_median": 302,
            "title": "Harry Potter and the Philosopher's Stone",
            "subject": [
                "Ghosts",
                "Monsters",
                "Vampires",
                "Witches",
                "Challenges and Overcoming Obstacles",
                "Magic and Supernatural",
                "Cleverness",
                "School Life",
                "school stories",
                "Wizards",
                "Magic",
                "MAGIA",
                "MAGOS",
                "Juvenile fiction",
                "Fiction",
                "NOVELAS INGLESAS",
                "Schools",
                "orphans",
                "fantasy fiction",
                "England in fiction",
                "Witches in fiction",
                "Wizards in fiction",
                "Alchemy",
                "New York Times bestseller",
                "Juvenile literature",
                "Magic in fiction",
                "Open Library Staff Picks",
                "Juvenile audience",
                "Children's stories",
                "Juvenile works",
                "Schools in fiction",
                "Fantasy",
                "Hogwarts School of Witchcraft and Wizardry (Imaginary place)",
                "Harry Potter (Fictitious character)",
                "Ficción juvenil",
                "Escuelas",
                "Hogwarts School of Witchcraft and Wizardry (Imaginary organization)",
                "Translations from English",
                "Chinese fiction",
                "Hermione Granger (Fictitious character)",
                "Reading Level-Grade 9",
                "Reading Level-Grade 11",
                "Reading Level-Grade 10",
                "Reading Level-Grade 12",
                "Hogwarts school of witchcraft and wizardry (imaginary organization), fiction",
                "Children's fiction",
                "Schools, fiction",
                "England, fiction",
                "Potter, harry (fictitious character), fiction",
                "Wizards, fiction",
                "Magic, fiction",
                "Fiction, fantasy, general",
                "Magier",
                "Fabeltiere",
                "Lehrling",
                "Kinderbuch",
                "Stein der Weisen",
                "Ungeheuer",
                "Junge",
                "English language",
                "Translating into Welsh",
                "Modern history to 20th century: c 1700 to c 1900",
                "Literary theory",
                "English literature",
                "Ron Weasley (Fictitious character)",
                "Latin language materials",
                "Romans, nouvelles, etc. pour la jeunesse",
                "Poudlard, école de sorcellerie (Organisation imaginaire)",
                "Sorciers",
                "Sorcières",
                "Magie",
                "Internats",
                "Adventure and adventurers, fiction",
                "Action & Adventure",
                "Fantasy & Magic",
                "Social Themes",
                "Friendship",
                "Harry Potter (Fictional character)",
                "Friendship, fiction",
                "German language materials",
                "Witchcraft, fiction",
                "Wizard",
                "NOVELAS FANTÁSTICAS",
                "NOVELAS JUVENILES INGLESAS",
                "LITERATURA JUVENIL ESTADOUNIDENSE",
                "Écoles",
                "Hechicería",
                "Novela juvenil",
                "Ingleterra",
                "Mystery",
                "roman",
                "English Fantasy literature",
                "Translations into Marathi",
                "English fiction",
                "Translations into Chinese",
                "Children - harry potter",
                "Teen fiction",
                "Children - fiction & literature",
                "Science fiction & fantasy",
                "Fiction - people",
                "Places & cultures",
                "Adventure",
                "Supernatural",
                "harry potter",
                "j.k rowling",
                "spanish"
            ],
            "person": [
                "Harry Potter",
                "Ron Weasley",
                "Hermione Granger",
                "Neville Longbottom",
                "Rubeus Hagrid",
                "Albus Dumbledore",
                "Minerva McGonagall",
                "Nicolas Flamel",
                "Norbert",
                "Sorting Hat",
                "Severus Snape",
                "Quirinus Quirrell",
                "Petunia Dursley",
                "Draco Malfoy",
                "Argus Filch",
                "Vernon Dursley",
                "Dudley Dursley",
                "Fred Weasley",
                "George Weasley",
                "Ginny Weasley",
                "Molly Weasley",
                "Percy Weasley",
                "Vincent Crabbe",
                "Gregory Goyle",
                "Lee Jordan",
                "Scabbers",
                "Hannah Abbott",
                "Bloody Baron",
                "Susan Bones",
                "Terry Boot",
                "Mandy Brocklehurst",
                "Lavender Brown",
                "Millicent Bulstrode",
                "Nearly Headless Nick",
                "Fat Friar",
                "Fat Lady",
                "Justin Finch-Fetchley",
                "Seamus Finnigan",
                "Morag MacDougal",
                "Lily Moon",
                "Pansy Parkinson",
                "Padma Patil",
                "Parvati Patil",
                "Peeves",
                "Dean Thomas",
                "Lisa Turpin",
                "Blaise Zabini",
                "Harry Potter (Fictitious character)"
            ],
            "ratings_average": 4.232846,
            "readinglog_count": 19794,
            "subject_key": [
                "action__adventure",
                "adventure",
                "adventure_and_adventurers_fiction",
                "alchemy",
                "challenges_and_overcoming_obstacles",
                "children's_fiction",
                "children's_stories",
                "children_-_fiction__literature",
                "children_-_harry_potter",
                "chinese_fiction",
                "cleverness",
                "england_fiction",
                "england_in_fiction",
                "english_fantasy_literature",
                "english_fiction",
                "english_language",
                "english_literature",
                "escuelas",
                "fabeltiere",
                "fantasy",
                "fantasy__magic",
                "fantasy_fiction",
                "ficción_juvenil",
                "fiction",
                "fiction_-_people",
                "fiction_fantasy_general",
                "friendship",
                "friendship_fiction",
                "german_language_materials",
                "ghosts",
                "harry_potter",
                "harry_potter_(fictional_character)",
                "harry_potter_(fictitious_character)",
                "hechicería",
                "hermione_granger_(fictitious_character)",
                "hogwarts_school_of_witchcraft_and_wizardry_(imaginary_organization)",
                "hogwarts_school_of_witchcraft_and_wizardry_(imaginary_organization)_fiction",
                "hogwarts_school_of_witchcraft_and_wizardry_(imaginary_place)",
                "ingleterra",
                "internats",
                "j.k_rowling",
                "junge",
                "juvenile_audience",
                "juvenile_fiction",
                "juvenile_literature",
                "juvenile_works",
                "kinderbuch",
                "latin_language_materials",
                "lehrling",
                "literary_theory",
                "literatura_juvenil_estadounidense",
                "magia",
                "magic",
                "magic_and_supernatural",
                "magic_fiction",
                "magic_in_fiction",
                "magie",
                "magier",
                "magos",
                "modern_history_to_20th_century_c_1700_to_c_1900",
                "monsters",
                "mystery",
                "new_york_times_bestseller",
                "novela_juvenil",
                "novelas_fantásticas",
                "novelas_inglesas",
                "novelas_juveniles_inglesas",
                "open_library_staff_picks",
                "orphans",
                "places__cultures",
                "potter_harry_(fictitious_character)_fiction",
                "poudlard_école_de_sorcellerie_(organisation_imaginaire)",
                "reading_level-grade_10",
                "reading_level-grade_11",
                "reading_level-grade_12",
                "reading_level-grade_9",
                "roman",
                "romans_nouvelles_etc._pour_la_jeunesse",
                "ron_weasley_(fictitious_character)",
                "school_life",
                "school_stories",
                "schools",
                "schools_fiction",
                "schools_in_fiction",
                "science_fiction__fantasy",
                "social_themes",
                "sorciers",
                "sorcières",
                "spanish",
                "stein_der_weisen",
                "supernatural",
                "teen_fiction",
                "translating_into_welsh",
                "translations_from_english",
                "translations_into_chinese",
                "translations_into_marathi",
                "ungeheuer",
                "vampires",
                "witchcraft_fiction",
                "witches",
                "witches_in_fiction",
                "wizard",
                "wizards",
                "wizards_fiction",
                "wizards_in_fiction",
                "écoles"
            ]
        },
        {
            "author_key": [
                "OL9180803A"
            ],
            "author_name": [
                "Ana Huang"
            ],
            "first_publish_year": 2021,
            "language": [
                "eng",
                "fre",
                "spa"
            ],
            "number_of_pages_median": 358,
            "title": "Twisted Love",
            "subject": [
                "Fiction, romance, multicultural & interracial",
                "Fiction, romance, new adult",
                "Fiction, romance, contemporary",
                "nyt:combined-print-and-e-book-fiction=2023-07-02",
                "New York Times bestseller",
                "Romance",
                "contemporary romance",
                "new adult romance",
                "brother's best friend",
                "forbidden love",
                "dark romance",
                "grumpy-sunshine",
                "angst",
                "love triangle",
                "self-discovery",
                "redemption",
                "Serie:Twisted"
            ],
            "ratings_average": 3.78125,
            "readinglog_count": 12703,
            "subject_key": [
                "angst",
                "brother's_best_friend",
                "contemporary_romance",
                "dark_romance",
                "fiction_romance_contemporary",
                "fiction_romance_multicultural__interracial",
                "fiction_romance_new_adult",
                "forbidden_love",
                "grumpy-sunshine",
                "love_triangle",
                "new_adult_romance",
                "new_york_times_bestseller",
                "nytcombined-print-and-e-book-fiction2023-07-02",
                "redemption",
                "romance",
                "self-discovery",
                "serietwisted"
            ]
        },
        {
            "author_key": [
                "OL234664A"
            ],
            "author_name": [
                "George R. R. Martin"
            ],
            "first_publish_year": 1996,
            "language": [
                "ind",
                "spa",
                "eng",
                "gle",
                "ger",
                "fre",
                "srp",
                "por",
                "swe",
                "dan",
                "rus",
                "chi",
                "jpn",
                "pol"
            ],
            "lccn": [
                "2011051999",
                "95043936",
                "2012454711",
                "2011380226"
            ],
            "number_of_pages_median": 802,
            "title": "A Game of Thrones",
            "subject": [
                "Adult",
                "Action & Adventure",
                "Fantasy",
                "High Fantasy",
                "Epic",
                "Epic Fantasy",
                "Epic Fiction",
                "Epic Literature",
                "Fiction, fantasy, epic",
                "Fiction, fantasy, general",
                "Science Fiction",
                "Fantastic Fiction",
                "Fiction",
                "Ficción",
                "Moral Ambiguity",
                "Betrayal",
                "Loyalty",
                "Family",
                "Revenge",
                "Vengeance",
                "Bien y mal",
                "Civil War",
                "War and Conflict",
                "Imaginary Wars and Battles",
                "Guerras imaginarias",
                "Politics",
                "Intrigue",
                "Feudalism",
                "Royalty and Nobility",
                "Kings and Rulers",
                "Knights",
                "Courts and Courtiers",
                "Seasons",
                "Invierno",
                "Trial by Combat",
                "Voyages and Travels",
                "Walls",
                "Penal Colonies",
                "Magic",
                "Dragons",
                "Supernatural",
                "Wights",
                "Folk Healers",
                "Incest",
                "Forced Marriage",
                "Persistent Vegetative States",
                "Imaginary Places",
                "Seven Kingdoms (Imaginary Place)",
                "Hugo Award Winner",
                "Ignotus Award Winner",
                "Locus Award Winner",
                "New York Times Bestseller",
                "Fantasy fiction"
            ],
            "person": [
                "Eddard Stark",
                "Catelyn Stark",
                "Robb Stark",
                "Sansa Stark",
                "Arya Stark",
                "Bran Stark",
                "Rickon Stark",
                "Jon Snow",
                "Theon Greyjoy",
                "Luwin",
                "Rodrik Cassel",
                "Jory Cassel",
                "Vayon Poole",
                "Jeyne Poole",
                "Alyn",
                "Tomard",
                "Hallis Mollen",
                "Harwin",
                "Mordane",
                "Mikken",
                "Old Nan",
                "Hodor",
                "Osha",
                "Syrio Forel",
                "Rickard Karstark",
                "Harrion Karstark",
                "Eddard Karstark",
                "Torrhen Karstark",
                "Galbart Glover",
                "Robett Glover",
                "Mors Umber",
                "Hother Umber",
                "Jon Umber (the Greatjon)",
                "Jon Umber (the Smalljon)",
                "Maege Mormont",
                "Wylis Manderly",
                "Wendel Manderly",
                "Roose Bolton",
                "Hoster Tully",
                "Edmure Tully",
                "Brynden Tully",
                "Robin Ryger",
                "Utherydes Wayn",
                "Tytos Blackwood",
                "Jonos Bracken",
                "Jason Mallister",
                "Patrek Mallister",
                "Marq Piper",
                "Walder Frey",
                "Stevron Frey",
                "Walder Frey (Black Walder)",
                "Emmon Frey",
                "Aenys Frey",
                "Jared Frey",
                "Hosteen Frey",
                "Merrett Frey",
                "Walder Frey (Little Walder)",
                "Lothar Frey",
                "Walder Frey (Big Walder)",
                "Walder Rivers",
                "Lysa Arryn",
                "Robert Arryn",
                "Yohn Royce",
                "Robar Royce",
                "Nestor Royce",
                "Mya Stone",
                "Lyn Corbray",
                "Anya Waynwood",
                "Colemon",
                "Mord",
                "Robert Baratheon",
                "Joffrey Baratheon",
                "Myrcella Baratheon",
                "Tommen Baratheon",
                "Renly Baratheon",
                "Bryce Caron",
                "Tywin Lannister",
                "Cersei Lannister",
                "Jaime Lannister",
                "Tyrion Lannister",
                "Kevan Lannister",
                "Lancel Lannister",
                "Ilyn Payne",
                "Podrick Payne",
                "Bronn",
                "Sandor Clegane",
                "Gregor Clegane",
                "Addam Marbrand",
                "Harys Swyft",
                "Loras Tyrell",
                "Horas Redwyne",
                "Hobber Redwyne",
                "Barristan Selmy",
                "Arys Oakheart",
                "Boros Blount",
                "Mandon Moore",
                "Meryn Trant",
                "Preston Greenfield",
                "Balon Swann",
                "Petyr Baelish",
                "Varys",
                "Pycelle",
                "Gyles Rosby",
                "Aron Santagar",
                "Janos Slynt",
                "Dontos Hollard",
                "Lothor Brune",
                "Jalabhar Xho",
                "Gendry",
                "Marillion",
                "Chataya",
                "Shae",
                "Timett",
                "Shagga",
                "Beric Dondarrion",
                "Thoros of Myr",
                "Jeor Mormont",
                "Aemon",
                "Benjen Stark",
                "Othell Yarwyck",
                "Bowen Marsh",
                "Donal Noye",
                "Alliser Thorne",
                "Dywen",
                "Yoren",
                "Waymar Royce",
                "Chett",
                "Samwell Tarly",
                "Grenn",
                "Pypar",
                "Dareon",
                "Jaremy Rykker",
                "Three-eyed crow",
                "Viserys Targaryen",
                "Daenerys Targaryen",
                "Jorah Mormont",
                "Illyrio Mopatis",
                "Drogo",
                "Qotho",
                "Cohollo",
                "Haggo",
                "Rakharo",
                "Jhogo",
                "Aggo",
                "Doreah",
                "Irri",
                "Jhiqui",
                "Mirri Maz Duur"
            ],
            "ratings_average": 4.217765,
            "readinglog_count": 11878,
            "subject_key": [
                "action__adventure",
                "adult",
                "betrayal",
                "bien_y_mal",
                "civil_war",
                "courts_and_courtiers",
                "dragons",
                "epic",
                "epic_fantasy",
                "epic_fiction",
                "epic_literature",
                "family",
                "fantastic_fiction",
                "fantasy",
                "fantasy_fiction",
                "feudalism",
                "ficción",
                "fiction",
                "fiction_fantasy_epic",
                "fiction_fantasy_general",
                "folk_healers",
                "forced_marriage",
                "guerras_imaginarias",
                "high_fantasy",
                "hugo_award_winner",
                "ignotus_award_winner",
                "imaginary_places",
                "imaginary_wars_and_battles",
                "incest",
                "intrigue",
                "invierno",
                "kings_and_rulers",
                "knights",
                "locus_award_winner",
                "loyalty",
                "magic",
                "moral_ambiguity",
                "new_york_times_bestseller",
                "penal_colonies",
                "persistent_vegetative_states",
                "politics",
                "revenge",
                "royalty_and_nobility",
                "science_fiction",
                "seasons",
                "seven_kingdoms_(imaginary_place)",
                "supernatural",
                "trial_by_combat",
                "vengeance",
                "voyages_and_travels",
                "walls",
                "war_and_conflict",
                "wights"
            ]
        },
        {
            "author_key": [
                "OL10218224A"
            ],
            "author_name": [
                "H. D. Carlton"
            ],
            "first_publish_year": 2021,
            "language": [
                "spa",
                "eng",
                "ger"
            ],
            "number_of_pages_median": 606,
            "title": "Haunting Adeline",
            "subject": [
                "collectionID:YDarkromance",
                "Fiction, romance, general",
                "Fiction, thrillers, suspense",
                "Young adult fiction, romance, general",
                "Young adult fiction, fantasy, dark fantasy",
                "nyt:trade-fiction-paperback=2024-09-15",
                "New York Times bestseller"
            ],
            "ratings_average": 3.579365,
            "readinglog_count": 9835,
            "subject_key": [
                "collectionidydarkromance",
                "fiction_romance_general",
                "fiction_thrillers_suspense",
                "new_york_times_bestseller",
                "nyttrade-fiction-paperback2024-09-15",
                "young_adult_fiction_fantasy_dark_fantasy",
                "young_adult_fiction_romance_general"
            ]
        },
        {
            "author_key": [
                "OL7315784A"
            ],
            "author_name": [
                "Colleen Hoover"
            ],
            "first_publish_year": 2022,
            "language": [
                "por",
                "eng"
            ],
            "lccn": [
                "2022942782",
                "2022945942"
            ],
            "number_of_pages_median": 344,
            "title": "It Starts with Us",
            "subject": [
                "Contemporary",
                "Romance",
                "Friendship",
                "Fiction",
                "Young Adult Fiction",
                "collectionid:nyt2020s",
                "American literature"
            ],
            "person": [
                "Colleen Hoover",
                "Lily",
                "Ryle",
                "Atlas"
            ],
            "ratings_average": 3.9911504,
            "readinglog_count": 16496,
            "subject_key": [
                "american_literature",
                "collectionidnyt2020s",
                "contemporary",
                "fiction",
                "friendship",
                "romance",
                "young_adult_fiction"
            ]
        },
        {
            "author_key": [
                "OL7115219A"
            ],
            "author_name": [
                "Sarah J. Maas"
            ],
            "first_publish_year": 2014,
            "language": [
                "eng",
                "pol",
                "fre",
                "por",
                "ger",
                "spa",
                "tur",
                "ukr"
            ],
            "lccn": [
                "2015042138"
            ],
            "number_of_pages_median": 640,
            "title": "A Court of Mist and Fury",
            "subject": [
                "Fantasy",
                "Fiction",
                "Fairies",
                "Blessing and cursing",
                "Fantasy fiction",
                "Fairies, fiction",
                "nyt:young-adult-hardcover=2016-05-22",
                "New York Times bestseller",
                "nyt:young-adult-e-book=2016-05-22",
                "collectionID:TexChallenge2021",
                "collectionID:KellerChallenge",
                "collectionID:EanesChallenge",
                "collectionID:AlpineChallenge",
                "Adaptations",
                "Magic",
                "Courts and courtiers",
                "Fées",
                "Romans, nouvelles, etc. pour la jeunesse",
                "Cours et courtisans",
                "Fantasy & Magic",
                "Love & Romance",
                "Action & Adventure",
                "General",
                "series:A_Court_of_Thorns_and_Roses",
                "Children's fiction"
            ],
            "person": [
                "Tam Lin (Legendary character)",
                "Nesta Archeron",
                "Rhysand",
                "Lucien Vanserra",
                "Tamlin",
                "Elain Archeron",
                "Feyre Archeron",
                "Azriel",
                "Cassian",
                "Morrigan"
            ],
            "ratings_average": 3.9976525,
            "readinglog_count": 8972,
            "subject_key": [
                "action__adventure",
                "adaptations",
                "blessing_and_cursing",
                "children's_fiction",
                "collectionidalpinechallenge",
                "collectionideaneschallenge",
                "collectionidkellerchallenge",
                "collectionidtexchallenge2021",
                "cours_et_courtisans",
                "courts_and_courtiers",
                "fairies",
                "fairies_fiction",
                "fantasy",
                "fantasy__magic",
                "fantasy_fiction",
                "fiction",
                "fées",
                "general",
                "love__romance",
                "magic",
                "new_york_times_bestseller",
                "nytyoung-adult-e-book2016-05-22",
                "nytyoung-adult-hardcover2016-05-22",
                "romans_nouvelles_etc._pour_la_jeunesse",
                "seriesa_court_of_thorns_and_roses"
            ]
        },
        {
            "author_key": [
                "OL66700A"
            ],
            "author_name": [
                "Paulo Coelho"
            ],
            "first_publish_year": 1988,
            "language": [
                "eng",
                "gre",
                "por",
                "dut",
                "ind",
                "tur",
                "may",
                "vie",
                "ita",
                "dan",
                "chi",
                "rus",
                "spa",
                "pol",
                "ger",
                "fre",
                "kor",
                "tha",
                "urd"
            ],
            "lccn": [
                "92056413",
                "94042789",
                "98006950",
                "94028948",
                "2013041007",
                "2003276041",
                "92832950"
            ],
            "number_of_pages_median": 197,
            "title": "O Alquimista",
            "subject": [
                "Translations into Indonesian",
                "Voyages and travels",
                "Fiction",
                "Portuguese Fiction",
                "Self-realization",
                "Alchemists",
                "Young men",
                "Shepherds",
                "New York Times bestseller",
                "nyt:trade_fiction_paperback=2008-01-05",
                "nyt:trade_fiction_paperback=2007-12-02",
                "Fiction, visionary & metaphysical",
                "Spain, fiction",
                "FICTION / Literary",
                "BODY, MIND & SPIRIT / Spirituality / General",
                "BODY, MIND & SPIRIT / Inspiration & Personal Growth",
                "Fables",
                "Translations from English",
                "Thai fiction",
                "French language",
                "Reading materials",
                "Russian language edition",
                "Powieść brazylijska",
                "Tłumaczenia polskie",
                "Comics & graphic novels, general",
                "Mexican literature",
                "Alquimia",
                "Novela",
                "Pastores",
                "Andalucía (España)",
                "Alquimistas",
                "Large type books",
                "Fiction, fantasy, general",
                "Alchemy",
                "Quests (Expeditions)",
                "Literary",
                "BODY, MIND & SPIRIT",
                "Spirituality",
                "General",
                "Inspiration & Personal Growth",
                "Expeditions",
                "Parodies, imitations",
                "Comic books, strips",
                "Graphic novels"
            ],
            "person": [
                "Paulo Coelho",
                "Daniel Sampere",
                "Derek Ruiz",
                "Sea Lion Books",
                "HarperCollins"
            ],
            "ratings_average": 3.858407,
            "readinglog_count": 7197,
            "subject_key": [
                "alchemists",
                "alchemy",
                "alquimia",
                "alquimistas",
                "andalucía_(españa)",
                "body_mind__spirit",
                "body_mind__spirit__inspiration__personal_growth",
                "body_mind__spirit__spirituality__general",
                "comic_books_strips",
                "comics__graphic_novels_general",
                "expeditions",
                "fables",
                "fiction",
                "fiction__literary",
                "fiction_fantasy_general",
                "fiction_visionary__metaphysical",
                "french_language",
                "general",
                "graphic_novels",
                "inspiration__personal_growth",
                "large_type_books",
                "literary",
                "mexican_literature",
                "new_york_times_bestseller",
                "novela",
                "nyttrade_fiction_paperback2007-12-02",
                "nyttrade_fiction_paperback2008-01-05",
                "parodies_imitations",
                "pastores",
                "portuguese_fiction",
                "powieść_brazylijska",
                "quests_(expeditions)",
                "reading_materials",
                "russian_language_edition",
                "self-realization",
                "shepherds",
                "spain_fiction",
                "spirituality",
                "thai_fiction",
                "translations_from_english",
                "translations_into_indonesian",
                "tłumaczenia_polskie",
                "voyages_and_travels",
                "young_men"
            ]
        },
        {
            "author_key": [
                "OL7093600A"
            ],
            "author_name": [
                "E. L. James"
            ],
            "first_publish_year": 2000,
            "language": [
                "pol",
                "ita",
                "rus",
                "fre",
                "chi",
                "ger",
                "spa",
                "dut",
                "jpn",
                "srp",
                "eng",
                "heb",
                "hin",
                "vie",
                "tur"
            ],
            "lccn": [
                "2012464986",
                "2012376657",
                "2012372219",
                "2015300004",
                "2012048082"
            ],
            "number_of_pages_median": 544,
            "title": "50 Fifty Shades of Grey",
            "subject": [
                "Man-woman relationships, fiction",
                "FICTION / Contemporary Women",
                "Sexual dominance and submission",
                "FICTION / Romance / Contemporary",
                "Dominance (Psychology)",
                "College students",
                "Businessmen",
                "Adultery",
                "Contemporary Women",
                "Contemporary",
                "Romance",
                "Fiction, erotica",
                "nyt:trade-fiction-paperback=2012-03-25",
                "New York Times bestseller",
                "Sexual attraction",
                "Fiction, erotica, general",
                "Large type books",
                "Businesspeople",
                "Erotic stories",
                "Love stories",
                "Domination et soumission (Sexualite)",
                "Romans, nouvelles",
                "Vietnamese language materials",
                "Gens d'affaires",
                "Relations entre hommes et femmes",
                "Domination et soumission (Sexualité)",
                "English literature",
                "erotic",
                "novel",
                "Relaciones hombre-mujer",
                "Ficción",
                "Adulterio",
                "Novela",
                "Erotic fiction",
                "NOVELA INGLESA",
                "LITERATURA INGLESA",
                "NOVELA EROTICA",
                "Translations into Hindi",
                "Histoires érotiques",
                "Étudiants",
                "Women college students",
                "Authors",
                "Self-realization",
                "Dating violence",
                "Fiction",
                "Man-woman relationships"
            ],
            "person": [
                "Anastasia Steele",
                "Christian Grey",
                "Kate Kavanagh",
                "José Rodriguez",
                "Mia Grey",
                "Elliot Grey"
            ],
            "ratings_average": 3.9471948,
            "readinglog_count": 6380,
            "subject_key": [
                "adulterio",
                "adultery",
                "authors",
                "businessmen",
                "businesspeople",
                "college_students",
                "contemporary",
                "contemporary_women",
                "dating_violence",
                "dominance_(psychology)",
                "domination_et_soumission_(sexualite)",
                "domination_et_soumission_(sexualité)",
                "english_literature",
                "erotic",
                "erotic_fiction",
                "erotic_stories",
                "ficción",
                "fiction",
                "fiction__contemporary_women",
                "fiction__romance__contemporary",
                "fiction_erotica",
                "fiction_erotica_general",
                "gens_d'affaires",
                "histoires_érotiques",
                "large_type_books",
                "literatura_inglesa",
                "love_stories",
                "man-woman_relationships",
                "man-woman_relationships_fiction",
                "new_york_times_bestseller",
                "novel",
                "novela",
                "novela_erotica",
                "novela_inglesa",
                "nyttrade-fiction-paperback2012-03-25",
                "relaciones_hombre-mujer",
                "relations_entre_hommes_et_femmes",
                "romance",
                "romans_nouvelles",
                "self-realization",
                "sexual_attraction",
                "sexual_dominance_and_submission",
                "translations_into_hindi",
                "vietnamese_language_materials",
                "women_college_students",
                "étudiants"
            ]
        },
        {
            "author_key": [
                "OL21594A"
            ],
            "author_name": [
                "Jane Austen"
            ],
            "first_publish_year": 1813,
            "language": [
                "eng",
                "por",
                "fin",
                "hun",
                "dut",
                "ind",
                "vie",
                "ita",
                "guj",
                "swe",
                "rus",
                "spa",
                "chi",
                "mul",
                "pol",
                "ger",
                "pan",
                "hin",
                "fre",
                "cor",
                "tam",
                "sin",
                "cze",
                "srp",
                "kor",
                "jpn"
            ],
            "lccn": [
                "2008926774",
                "2010046436",
                "2011049592",
                "2004063683",
                "95021308",
                "65006563",
                "2012464503",
                "00007090",
                "97908750",
                "2003096589",
                "82011774",
                "02029257",
                "86220536",
                "gb90003359",
                "50007332",
                "80013177",
                "2009279693",
                "2004269972",
                "2003102755",
                "45006105",
                "2002192567",
                "2001265847",
                "2013039364",
                "97140981",
                "80070747",
                "49004277",
                "2002514983",
                "00694648",
                "81126202",
                "2008371999",
                "51002270",
                "46019197",
                "90035222",
                "84081185",
                "63014766",
                "2011287276",
                "2010537038",
                "72541679",
                "95006310",
                "2007023681",
                "2009026164",
                "40006162",
                "80111876",
                "00269143",
                "41003901",
                "2003265779",
                "30026942",
                "2006284315",
                "2006281130",
                "2008277621",
                "62018385",
                "2005049349",
                "67012360",
                "gb54003198",
                "00702782",
                "61018550",
                "97190825",
                "91052940",
                "88063173",
                "2008297285",
                "2010013236",
                "18007296",
                "50006142",
                "30029995",
                "92032426",
                "95084040",
                "79110566",
                "2004060928",
                "95119381",
                "gb89009876",
                "00007087",
                "94135209",
                "46006883",
                "20017968",
                "84060894",
                "93100474",
                "a62005679",
                "2005565515",
                "2011456792",
                "99025620",
                "2004100759",
                "72186963",
                "66078549",
                "18001222",
                "00065908",
                "49008849",
                "2009510490",
                "60024373",
                "71002815",
                "2019939272",
                "34028479",
                "2006007530",
                "2006049949",
                "98812656",
                "83007301",
                "56013877",
                "95000849",
                "68094887",
                "95069125",
                "2009924951",
                "99462506",
                "2012025584"
            ],
            "number_of_pages_median": 351,
            "title": "Pride and Prejudice",
            "subject": [
                "Fiction, Romance, Historical, Regency",
                "British and Irish fiction (fictional works by one author)",
                "Brothers and sisters",
                "Courtship",
                "Drama",
                "English fiction",
                "English literature",
                "Families",
                "Family",
                "Family life",
                "Family relations",
                "Fiction Classics",
                "History",
                "Interpersonal relations",
                "Literary Fiction",
                "Love stories",
                "manners",
                "Manners and customs",
                "marriage",
                "Sisters",
                "Social classes",
                "Social life and customs",
                "Upper class",
                "wealth",
                "Women in England",
                "young ladies",
                "Young women",
                "entail",
                "Young women, fiction",
                "Sisters, fiction",
                "Fiction, family life, general",
                "England, fiction",
                "Man-woman relationships, fiction",
                "Roman anglais",
                "Classes sociales",
                "Romans, nouvelles",
                "Sœurs",
                "Amours",
                "Jeunes femmes",
                "Familles",
                "Mœurs et coutumes\"",
                "Clases sociales",
                "Novela",
                "Jóvenes (Mujeres)",
                "Cortejo amoroso",
                "Hermanas",
                "Cuentos de amor",
                "Fiction, coming of age",
                "Fiction, romance, general",
                "Great britain, social life and customs, fiction",
                "Readers",
                "Prejudices",
                "Romance fiction",
                "Historical fiction",
                "Classical literature",
                "Domestic fiction",
                "English language, textbooks for foreign speakers",
                "Women, fiction",
                "Adaptations",
                "Gentry",
                "Mate selection",
                "Fiction, romance, historical, general",
                "English literature (collections)",
                "Coloring books",
                "Fiction, family life",
                "Language and languages, study and teaching",
                "Emoticons",
                "Drama (dramatic works by one author)",
                "Feelings",
                "Class",
                "Englisch",
                "Roman",
                "Sociala klasser i litteraturen",
                "Prophecies",
                "Great britain",
                "Reading level-grade 7",
                "Reading level-grade 9",
                "Reading level-grade 8",
                "Reading level-grade 11",
                "Reading level-grade 10",
                "Reading level-grade 12",
                "Large type books",
                "Fiction, romance, historical",
                "Austen, jane, 1775-1817",
                "Literature and fiction (general)",
                "English literature, history and criticism",
                "England",
                "Художественная литература -- Великобритания -- Английская литература -- 1-ая пол. 19 в. -- Романы",
                "Novel",
                "Fiction",
                "Long Now Manual for Civilization",
                "Elizabeth Bennet (Fictitious character)",
                "Fitzwilliam Darcy (Fictitious character)",
                "Pride and prejudice (Austen, Jane)",
                "Mr. Collins (Fictitious character)"
            ],
            "person": [
                "Elizabeth Bennet",
                "Fitzwilliam Darcy",
                "Charlotte Lucas",
                "George Wickham",
                "Mr. Bennet",
                "Mrs. Bennet",
                "Jane Bennet",
                "Mary Bennet",
                "Catherine Bennet",
                "Lydia Bennet",
                "Charles Bingley",
                "Caroline Bingley",
                "William Collins",
                "Catherine de Bourgh"
            ],
            "ratings_average": 4.1552796,
            "readinglog_count": 5984,
            "subject_key": [
                "adaptations",
                "amours",
                "austen_jane_1775-1817",
                "british_and_irish_fiction_(fictional_works_by_one_author)",
                "brothers_and_sisters",
                "clases_sociales",
                "class",
                "classes_sociales",
                "classical_literature",
                "coloring_books",
                "cortejo_amoroso",
                "courtship",
                "cuentos_de_amor",
                "domestic_fiction",
                "drama",
                "drama_(dramatic_works_by_one_author)",
                "elizabeth_bennet_(fictitious_character)",
                "emoticons",
                "england",
                "england_fiction",
                "englisch",
                "english_fiction",
                "english_language_textbooks_for_foreign_speakers",
                "english_literature",
                "english_literature_(collections)",
                "english_literature_history_and_criticism",
                "entail",
                "families",
                "familles",
                "family",
                "family_life",
                "family_relations",
                "feelings",
                "fiction",
                "fiction_classics",
                "fiction_coming_of_age",
                "fiction_family_life",
                "fiction_family_life_general",
                "fiction_romance_general",
                "fiction_romance_historical",
                "fiction_romance_historical_general",
                "fiction_romance_historical_regency",
                "fitzwilliam_darcy_(fictitious_character)",
                "gentry",
                "great_britain",
                "great_britain_social_life_and_customs_fiction",
                "hermanas",
                "historical_fiction",
                "history",
                "interpersonal_relations",
                "jeunes_femmes",
                "jóvenes_(mujeres)",
                "language_and_languages_study_and_teaching",
                "large_type_books",
                "literary_fiction",
                "literature_and_fiction_(general)",
                "long_now_manual_for_civilization",
                "love_stories",
                "man-woman_relationships_fiction",
                "manners",
                "manners_and_customs",
                "marriage",
                "mate_selection",
                "mr._collins_(fictitious_character)",
                "mœurs_et_coutumes",
                "novel",
                "novela",
                "prejudices",
                "pride_and_prejudice_(austen_jane)",
                "prophecies",
                "readers",
                "reading_level-grade_10",
                "reading_level-grade_11",
                "reading_level-grade_12",
                "reading_level-grade_7",
                "reading_level-grade_8",
                "reading_level-grade_9",
                "roman",
                "roman_anglais",
                "romance_fiction",
                "romans_nouvelles",
                "sisters",
                "sisters_fiction",
                "social_classes",
                "social_life_and_customs",
                "sociala_klasser_i_litteraturen",
                "sœurs",
                "upper_class",
                "wealth",
                "women_fiction",
                "women_in_england",
                "young_ladies",
                "young_women",
                "young_women_fiction",
                "художественная_литература_--_великобритания_--_английская_литература_--_1-ая_пол._19_в._--_романы"
            ]
        }
    ])


    return (
        <div>
            <BookCollection groupTitle={'Trending books of 2025'} bookData={tempData} />
            <BookCollection groupTitle={'Popular Fiction'} bookData={tempData} />
            <BookCollection groupTitle={'Popular Non-Fiction'} bookData={tempData} />
        </div>
    )
}

export default MainBody